name: Fullbright
main: com.applenick.Fullbright.Fullbright
version: 1.1
description: Fullbright is an Open Source plugin we created to allow players to see have full brightness anywhere. You can view the plugin at https://github.com/Ice-Stone/Fullbright
author: AppleNick